USE springboottask;
CREATE TABLE IF NOT EXISTS user (
    id VARCHAR(36) PRIMARY KEY NOT NULL,
    email VARCHAR(50) NOT NULL,
    name VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS article (
   id VARCHAR(36) PRIMARY KEY NOT NULL ,
   userid VARCHAR(36),
   name VARCHAR(50) NOT NULL,
   text VARCHAR(255) NOT NULL,
   FOREIGN KEY (userid) REFERENCES user(id) ON DELETE CASCADE
);
